# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-02 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_tabs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmssingletab',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_tabs_cmssingletab', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='cmstabslist',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_tabs_cmstabslist', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
